import "./globals.css";

import { Inter } from "next/font/google";
import type { Metadata } from "next";
import ReactQueryProvider from "@/lib/store/providers/reactQuery";
import StoreProvider from "@/lib/store/providers/redux";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <ReactQueryProvider>{children}</ReactQueryProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
